export enum ActivityCategoryType {
  TRANSPORT = 'TRANSPORT',
  FOOD = 'FOOD',
  ENERGY = 'ENERGY',
  WASTE = 'WASTE',
}

export enum GoalStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum GoalType {
  REDUCTION_PERCENTAGE = 'REDUCTION_PERCENTAGE',
  REDUCTION_ABSOLUTE = 'REDUCTION_ABSOLUTE',
  ACTIVITY_COUNT = 'ACTIVITY_COUNT',
  STREAK = 'STREAK',
}

export enum BadgeCategory {
  LOGGING = 'LOGGING',
  STREAK = 'STREAK',
  GOAL = 'GOAL',
  REDUCTION = 'REDUCTION',
  CATEGORY = 'CATEGORY',
  ENGAGEMENT = 'ENGAGEMENT',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REGISTER = 'REGISTER',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  ACCOUNT_DELETE = 'ACCOUNT_DELETE',
}

export enum PointSource {
  ACTIVITY_LOG = 'ACTIVITY_LOG',
  GOAL_COMPLETE = 'GOAL_COMPLETE',
  BADGE_UNLOCK = 'BADGE_UNLOCK',
  STREAK_MILESTONE = 'STREAK_MILESTONE',
}

export enum InsightType {
  HABIT_ANALYSIS = 'HABIT_ANALYSIS',
  PERSONALIZED_TIPS = 'PERSONALIZED_TIPS',
  WEEKLY_DIGEST = 'WEEKLY_DIGEST',
  ALTERNATIVES = 'ALTERNATIVES',
  PROJECTION = 'PROJECTION',
}

export enum InsightSource {
  GEMINI = 'GEMINI',
  GROQ = 'GROQ',
  RULE_BASED = 'RULE_BASED',
  CACHED = 'CACHED',
}

export enum MeasurementUnit {
  KM = 'KM',
  KG = 'KG',
  KWH = 'KWH',
  HOURS = 'HOURS',
  LITERS = 'LITERS',
  COUNT = 'COUNT',
  MEAL = 'MEAL',
}
