import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { Leaf, TrendingDown, Award, Sparkles, ArrowRight } from 'lucide-react';

export default function LandingPage() {
  return (
    <div className="flex flex-col items-center min-h-[calc(100vh-8rem)]">
      
      {/* ─── Hero Section ─── */}
      <section className="relative w-full max-w-4xl mx-auto pt-24 pb-32 text-center flex flex-col items-center justify-center animate-fade-in-up">
        <div className="absolute top-0 inset-x-0 h-64 bg-gradient-to-b from-leaf-pale/20 to-transparent pointer-events-none -z-10 rounded-full blur-3xl"></div>
        
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-leaf-pale/30 text-forest-light text-sm font-semibold mb-8 border border-leaf-pale/50 animate-slide-down delay-100">
          <Sparkles className="w-4 h-4" />
          <span>Your personal sustainability coach</span>
        </div>

        <h1 className="text-5xl md:text-7xl font-bold font-[family-name:var(--font-heading)] text-text leading-tight tracking-tight mb-6">
          Track less. <br />
          <span className="gradient-text">Impact more.</span>
        </h1>
        
        <p className="text-xl md:text-2xl text-text-secondary max-w-2xl mb-10 leading-relaxed font-light">
          Imprint helps you understand, track, and significantly reduce your carbon footprint through seamless logging and hyper-personalized AI insights.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 w-full">
          <Link href="/register" className="w-full sm:w-auto">
            <Button size="lg" className="w-full sm:w-auto text-lg shadow-lg shadow-forest/20 group">
              Start Your Journey
              <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
            </Button>
          </Link>
          <Link href="/login" className="w-full sm:w-auto">
            <Button variant="secondary" size="lg" className="w-full sm:w-auto text-lg">
              Sign In
            </Button>
          </Link>
        </div>
      </section>

      {/* ─── Features Grid ─── */}
      <section className="w-full max-w-6xl mx-auto pb-24 grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="card p-8 flex flex-col items-center text-center space-y-5 animate-fade-in-up delay-200">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-leaf-pale to-white shadow-inner flex items-center justify-center text-forest">
            <Leaf className="w-8 h-8" />
          </div>
          <h3 className="text-2xl font-bold font-[family-name:var(--font-heading)] text-text">Intelligent Tracking</h3>
          <p className="text-text-secondary leading-relaxed">
            Easily log your daily transport, food, and energy usage. We dynamically calculate precise CO₂e impact using ClimateIQ.
          </p>
        </div>

        <div className="card p-8 flex flex-col items-center text-center space-y-5 animate-fade-in-up delay-300">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-100 to-white shadow-inner flex items-center justify-center text-blue-600">
            <TrendingDown className="w-8 h-8" />
          </div>
          <h3 className="text-2xl font-bold font-[family-name:var(--font-heading)] text-text">AI Action Plans</h3>
          <p className="text-text-secondary leading-relaxed">
            Receive personalized, highly actionable recommendations generated by Gemini 2.0 based entirely on your unique lifestyle.
          </p>
        </div>

        <div className="card p-8 flex flex-col items-center text-center space-y-5 animate-fade-in-up delay-400">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-yellow-100 to-white shadow-inner flex items-center justify-center text-yellow-600">
            <Award className="w-8 h-8" />
          </div>
          <h3 className="text-2xl font-bold font-[family-name:var(--font-heading)] text-text">Gamified Goals</h3>
          <p className="text-text-secondary leading-relaxed">
            Set reduction targets, track progress dynamically over time, earn badges, and build lasting sustainable habits.
          </p>
        </div>
      </section>

    </div>
  );
}
