'use client';

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/Card';
import { Skeleton } from '@/components/ui/Skeleton';
import { Button } from '@/components/ui/Button';
import { api } from '@/lib/api';
import { Lightbulb, Target, TrendingDown, Sparkles } from 'lucide-react';

type Insight = {
  id: string;
  type: 'REDUCTION_TIP' | 'ACHIEVEMENT' | 'COMPARISON' | 'PERSONALIZED_TIPS' | 'HABIT_ANALYSIS';
  content: {
    title: string;
    description: string;
    emissionSavedPotential: number;
  };
  createdAt: string;
};

export default function InsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const fetchInsights = async () => {
    try {
      const { data } = await api.get('/insights');
      setInsights(data.data);
    } catch (error) {
      console.error('Failed to fetch insights', error);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  const generateInsights = async () => {
    setIsGenerating(true);
    setErrorMsg('');
    try {
      await api.post('/insights/generate');
      await fetchInsights();
    } catch (err: any) {
      console.error('Failed to generate insights', err);
      const msg = err.response?.data?.error?.message || 'Failed to generate insights. Please try again.';
      setErrorMsg(msg);
    } finally {
      setIsGenerating(false);
    }
  };

  const getIcon = (type: string) => {
    switch (type) {
      case 'REDUCTION_TIP': 
      case 'PERSONALIZED_TIPS': return <TrendingDown className="h-6 w-6 text-blue-600" />;
      case 'ACHIEVEMENT': return <Target className="h-6 w-6 text-green-600" />;
      case 'COMPARISON': 
      case 'HABIT_ANALYSIS': return <Lightbulb className="h-6 w-6 text-amber-500" />;
      default: return <Sparkles className="h-6 w-6 text-forest" />;
    }
  };

  const getTheme = (type: string) => {
    switch (type) {
      case 'REDUCTION_TIP':
      case 'PERSONALIZED_TIPS': return 'from-blue-50 to-white border-blue-100';
      case 'ACHIEVEMENT': return 'from-green-50 to-white border-green-100';
      case 'COMPARISON':
      case 'HABIT_ANALYSIS': return 'from-amber-50 to-white border-amber-100';
      default: return 'from-leaf-pale/20 to-white border-leaf-pale/50';
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6 animate-fade-in-up">
        <div>
          <Skeleton className="h-10 w-64 mb-2" />
          <Skeleton className="h-5 w-80" />
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Skeleton className="h-[400px] w-full lg:col-span-2 rounded-2xl" />
          <div className="space-y-6">
            <Skeleton className="h-32 w-full rounded-2xl" />
            <Skeleton className="h-32 w-full rounded-2xl" />
            <Skeleton className="h-32 w-full rounded-2xl" />
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in-up">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-gradient-to-r from-forest to-forest-light p-8 rounded-2xl text-white shadow-xl shadow-forest/20 relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Sparkles className="w-32 h-32" />
        </div>
        <div className="relative z-10">
          <h1 className="text-3xl font-bold font-[family-name:var(--font-heading)] tracking-tight flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-leaf-pale" /> AI Insights
          </h1>
          <p className="text-leaf-pale mt-2 max-w-lg">
            Personalized recommendations generated by Gemini 2.0 based entirely on your 30-day tracking history.
          </p>
        </div>
        <div className="relative z-10">
          <Button onClick={generateInsights} isLoading={isGenerating} className="!bg-white !text-forest hover:!bg-leaf-pale shadow-lg">
            Generate New Insights
          </Button>
        </div>
      </div>

      {errorMsg && (
        <div className="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl flex items-center justify-between text-sm animate-fade-in">
          <div className="flex items-center gap-2">
            <span className="font-semibold">Note:</span>
            <span>{errorMsg}</span>
          </div>
          <button onClick={() => setErrorMsg('')} className="text-red-500 hover:text-red-700 font-bold ml-4">
            Dismiss
          </button>
        </div>
      )}

      {insights.length === 0 ? (
        <Card className="border-dashed border-2 border-gray-200 bg-gray-50/50">
          <CardContent className="py-16 text-center text-text-muted">
            <Sparkles className="w-12 h-12 mx-auto mb-4 opacity-20" />
            <p className="text-lg font-medium text-text">No insights generated yet</p>
            <p className="text-sm mt-1 max-w-sm mx-auto">Click the button above to have AI analyze your recent activity and generate actionable reduction tips.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {insights.map((insight, idx) => (
            <Card key={insight.id} className={`flex flex-col border bg-gradient-to-br ${getTheme(insight.type)} shadow-sm hover:shadow-md transition-all delay-${(idx % 4 + 1) * 100}`}>
              <CardHeader className="flex flex-row items-start gap-4 space-y-0 pb-2">
                <div className="rounded-xl bg-white p-3 shadow-sm border border-gray-100">
                  {getIcon(insight.type)}
                </div>
                <div className="space-y-1 flex-1">
                  <CardTitle className="text-lg leading-tight">{insight.content.title}</CardTitle>
                  <CardDescription className="text-xs font-medium opacity-70">
                    {new Date(insight.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric' })}
                  </CardDescription>
                </div>
              </CardHeader>
              <CardContent className="flex-1 text-sm text-text-secondary leading-relaxed pt-2">
                {insight.content.description}
              </CardContent>
              {insight.content.emissionSavedPotential > 0 && (
                <div className="px-6 pb-6 mt-auto">
                  <div className="inline-flex items-center rounded-lg bg-white/60 px-3 py-1.5 text-xs font-bold text-forest border border-forest/10 shadow-sm w-full">
                    <TrendingDown className="w-4 h-4 mr-2" />
                    Potential Savings: {insight.content.emissionSavedPotential} kg CO₂e
                  </div>
                </div>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
